=== JuanCarlos92/DAM1_LenguajeMarcas/TAREAS/Tarea4/datos.dtd
<!ELEMENT tienda (disco)*>
<!ELEMENT disco (nombre, grupo, año, discografica)*>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT grupo (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT discografica (#PCDATA)>
<!ATTLIST disco formato (CD|LP|K7|MP3) #REQUIRED>

=== JuanCarlos92/DAM1_LenguajeMarcas/TAREAS/Tarea4/datos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tienda SYSTEM "datos.dtd">

<tienda>
  <disco  formato="LP">
    <nombre>Sgt. Pepper's Lonely Hearts Club Band</nombre>
    <grupo>The Beatles</grupo>
    <año>1967</año>
    <discografica>capitol</discografica>
  </disco>
  
  <disco formato="K7">
    <nombre>What's Going On</nombre>
    <grupo>Marvin Gaye</grupo>
    <año>1971</año>
    <discografica>Motown</discografica>
  </disco>
  
  <disco formato="LP">
    <nombre>Blood on the Tracks</nombre>
    <grupo>Bob Dylan</grupo>
    <año>1975</año>
    <discografica>Columbia</discografica>
  </disco>
  
  <disco formato="CD">
    <nombre>Back to Mono (1958-1969)</nombre>
    <grupo>Phil Spector</grupo>
    <año>1991</año>
    <discografica>Abkco</discografica>
  </disco>
  
    <disco formato="LP">
    <nombre>Physical Graffiti</nombre>
    <grupo>Led Zeppelin</grupo>
    <año>1975</año>
    <discografica>Atlantic</discografica>
  </disco>
  
  <disco formato="K7">
    <nombre>Back In Back</nombre>
    <grupo>AC/DC</grupo>
    <año>1980</año>
  <discografica>Atlantic</discografica>
  </disco>
</tienda>
